version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - favicon.ico
    - KyleMoodyResume_2015.pdf
    - styles/main.css
    - images/*
    
